AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: Database initialization function.
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 512
      Handler: com.sldd.dbinitializer.DbInitializerHandler
      CodeUri: /Users/georgy.saukov/Desktop/dev/work/ServerLessDbDemo/SLDBInitializer
      Runtime: java11
      Environment:
        Variables:
          DATABASE_ENDPOIT:
            Fn::ImportValue:
              Fn::Sub: "${Env}-DBClusterEndpoint"
          DATABASE_ENDPOIT_PORT:
            Fn::ImportValue:
              Fn::Sub: "${Env}-DBClusterEndpointPort"
          DATABASE_SECRETS:
            Fn::ImportValue:
              Fn::Sub: "${Env}-DBClusterSecrets"
