create table if not exists company_description
(
    id bigint generated by default as identity
    constraint "COMPANY_DESCRIPTION_pkey"
    primary key,
    company varchar(80) not null,
    discount integer not null,
    info varchar(512) not null,
    phone varchar(40) not null
    );

alter table company_description owner to serveles_db;

create table if not exists factory_description
(
    id bigint generated by default as identity
    constraint "FACTORY_DESCRIPTION_pkey"
    primary key,
    phone varchar(40) not null,
    position varchar(255) not null
    );

alter table factory_description owner to serveles_db;

create table if not exists product
(
    id bigint generated by default as identity
    constraint "PRODUCT_pkey"
    primary key,
    category varchar(180) not null,
    name varchar(180) not null,
    prime_cost integer not null,
    type varchar(120) not null
    );

alter table product owner to serveles_db;

create table if not exists product_details
(
    id bigint generated by default as identity
    constraint "PRODUCT_DETAILS_pkey"
    primary key,
    quantity integer not null,
    sell_cost integer not null,
    product_id bigint not null
    constraint fk_product_id
    references product
);

alter table product_details owner to serveles_db;

create table if not exists relation_type
(
    id bigint generated by default as identity
    constraint "RELATION_TYPE_pkey"
    primary key,
    company_description_id bigint
    constraint fk_company_description_id
    references company_description,
    factory_description_id bigint
    constraint fk_factory_description_id
    references factory_description
);

alter table relation_type owner to serveles_db;

create table if not exists role
(
    id bigint generated by default as identity
    constraint "ROLE_pkey"
    primary key,
    name varchar(60) not null
    constraint role_name_key
    unique
    );

alter table role owner to serveles_db;

create table if not exists user_description
(
    id bigint generated by default as identity
    constraint "USER_DESCRIPTION_pkey"
    primary key,
    relation_type_id bigint not null
    constraint fk_relation_type_id
    references relation_type,
    role_id bigint not null
    constraint fk_role_id
    references role
);

alter table user_description owner to serveles_db;

create table if not exists users
(
    id bigint generated by default as identity
    constraint "USERS_pkey"
    primary key,
    email varchar(180) not null
    constraint users_email_key
    unique,
    full_name varchar(255) not null,
    user_description_id bigint not null
    constraint fk_user_description_id
    references user_description
    );

alter table users owner to serveles_db;

create table if not exists auth_info_entity
(
    id bigint generated by default as identity
    constraint "AUTH_INFO_ENTITY_pkey"
    primary key,
    login varchar(255) not null,
    password varchar(100) not null,
    users_id bigint not null
    constraint fk_auth_users_id
    references users
    );

alter table auth_info_entity owner to serveles_db;

create table if not exists orders
(
    id bigint generated by default as identity
    constraint "ORDERS_pkey"
    primary key,
    cost bigint not null,
    end_date date not null,
    start_date date not null,
    status varchar(255) not null,
    users_id bigint not null
    constraint fk_users_id
    references users
    );

alter table orders owner to serveles_db;

create table if not exists orders_product_details
(
    orders_id bigint not null
    constraint fk_orders_id
    references orders,
    product_details_id bigint not null
    constraint orders_product_details_product_details_id_key
    unique
    constraint fk_product_details_id
    references product_details
);

alter table orders_product_details owner to serveles_db;
