AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: Database initialization function.

Parameters:
  Env:
    Type: String
    Description: environment
    Default: dev
    AllowedValues:
      - dev
      - uat
      - prd
  LambdaExecutionRole:
    Description: Arn of a lambda execution role with
    Type: String


Resources:
  SLDBInitializerLambda:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 512
      Role: !Ref LambdaExecutionRole
      Handler: com.sldd.dbinitializer.DbInitializerHandler::handleRequest
      Layers:
        - !Ref SLDBInitializerDependencyLayer
      CodeUri: s3://my-new-lambda-bucket-6328764287365/SLDBInitializer-0.1.0.jar
      Runtime: java11
      Environment:
        Variables:
          DATABASE_ENDPOINT:
            Fn::ImportValue:
              Fn::Sub: "${Env}-DBClusterEndpoint"
          DATABASE_ENDPOINT_PORT:
            Fn::ImportValue:
              Fn::Sub: "${Env}-DBClusterPort"
          DATABASE_SECRETS:
            Fn::ImportValue:
              Fn::Sub: "${Env}-DBSecrets"

  SLDBInitializerDependencyLayer:
    Type: 'AWS::Serverless::LayerVersion'
    compatibleRuntimes:
      - java11
    Properties:
      ContentUri: s3://my-new-lambda-bucket-6328764287365/SLDBInitializer-dependencies.zip

  InvokeSLDBInitializerLambda:
    Type: AWS::CloudFormation::CustomResource
    DependsOn: SLDBInitializerLambda
    Version: "1.0"
    Properties:
      ServiceToken: !GetAtt SLDBInitializerLambda.Arn
